### ISSUE TITLE
Fetch full know-their-names dataset.csv 

### ISSUE THREAD

**Issue by alqalamfilastin** [Zain-ul-din/awesome-palestine-apis#1]
https://github.com/Zain-ul-din/awesome-palestine-apis/blob/3fce6c46880935e192b140250700667f86e221be/crawlers/know-their-names/src/index.ts#L10

You can fetch the full dataset directly. No need to crawl site

https://datawrapper.dwcdn.net/SAgXc/2/dataset.csv

**Comment by Zain-ul-din** [comment]
Thank you for reaching out.
That's good i will add this link to resources list. however, we also have to provide JSON format of this data.

**Comment by Zain-ul-din** [comment]
@alqalamfilastin link has been added to readme.
